Rotor wash for ALS-Renderer
HHS81/ec135 pull request #32
Opened 2017-06-28 20:12 UTC by HHS81

This adds the needed nasal-script for the rotorwash effect on 3d-grass and water in ALS-Renderer.
To be used with latest FGFS 2017.3.0 or upcoming 2017.3.1

2017-06-28 22:15 UTC, HHS81 commented
some images:
![rotorwash1](https://user-images.githubusercontent.com/12649375/27662852-f2c9b7aa-5c5f-11e7-92f7-678882c225c5.jpg)
![rotorwash2](https://user-images.githubusercontent.com/12649375/27662853-f2cc2832-5c5f-11e7-8704-bcd1997710f8.jpg)
![rotorwash3](https://user-images.githubusercontent.com/12649375/27662854-f2ccc6f2-5c5f-11e7-9a9d-96501b69828a.jpg)

2017-06-29 19:12 UTC, SebDieBln reviewed
~~I did not see the effect in ALS, I still got the particles as usual. Are there any special settings to apply to observe the effect? (Beginner question from a Rembrandt guy 😃).~~
OK, as you said, it needs the nightly build 2017.3 or newer. I have the latest stable 2017.2.1 😞

2017-06-29 21:08 UTC, HHS81 commented
You can download the shader and .eff-files from FGData. No new fgfs.exe needed.

2017-06-29 21:11 UTC, HHS81 commented
First entry shows the needed files: https://sourceforge.net/p/flightgear/fgdata/commit_browser

2017-07-03 21:05 UTC, SebDieBln commented
OK, thanks! I have the effect now working in 2017.2.1.

2017-07-10 15:33 UTC, HHS81 commented
@SebDieBln 
And, do you like it?

2017-07-15 11:33 UTC, SebDieBln commented
Yes, I do like it! It looks really good.

What do you think of my points in the review?

2017-07-15 16:19 UTC, HHS81 commented
Ähm... which points? I'm a bit confused. :con
2017.3.1 will comes out soon or later and make use of new features.

2017-07-15 16:45 UTC, HHS81 commented
Accidently closed. Clumsy Fingers.....

2017-07-15 20:02 UTC, SebDieBln requested changes
I somehow started a review but did not finish it so everyone could see it. My mistake.

I think there are some issues that could be addressed before merging.

2017-07-15 20:02 UTC, SebDieBln commented on Nasal/rotor_wash.nas
> +# Preflight control surface check: elevator
This comment doesn't seem to match the code?

2017-07-15 20:02 UTC, SebDieBln commented on Nasal/rotor_wash.nas
> +var vpos = geo.viewer_position();
How about some indentation for the nasal code? I find it quite hard to read and maintain unindented code.

2017-07-15 20:02 UTC, SebDieBln commented on Nasal/rotor_wash.nas
> +settimer (wash_loop, 0.0);
Using `0.0` as the loop interval makes this loop run all the time. Is this intended/needed for the effect? Will this have performance issues?

2017-07-15 20:02 UTC, SebDieBln commented on Nasal/rotor_wash.nas
> +
I am missing a _pitch factor_ or something like that here. Looking at the code the effect will be the same regardless of whether the helicopter is (flight-)idling on the ground or hovering, whereas in reality there is no downwash from a helicopter producing no lift (though there might be some turbulence from the spinning blades).

2017-07-15 20:02 UTC, SebDieBln commented on Nasal/rotor_wash.nas
> +settimer (wash_loop, 0.0);
Should this be run in real-time instead of simulation-time? Changing the point of view when the simulation is paused causes the downwash to be drawn at the wrong position.
Maybe have two loops:
* real-time loop for the position
* simulation-time loop for the rest

2017-07-15 20:02 UTC, SebDieBln commented on Nasal/rotor_wash.nas
> +settimer (wash_loop, 0.0);
And it seems [settimer()](http://wiki.flightgear.org/Nasal_library#settimer.28.29) is somewhat deprecated. [maketimer()](http://wiki.flightgear.org/Nasal_library#maketimer.28.29) is the new way to go.

2017-07-15 20:53 UTC, HHS81 commented on Nasal/rotor_wash.nas
> +var vpos = geo.viewer_position();
Ah,  that was my mistake. Thorsten original Code didn't work,  so I tried another piece

2017-07-15 20:55 UTC, HHS81 commented on Nasal/rotor_wash.nas
> +
Yes,  I thought the same.

2017-07-15 20:57 UTC, HHS81 commented on Nasal/rotor_wash.nas
> +settimer (wash_loop, 0.0);
This is an effect of the shader according to Thorsten Renk. There is a comment about on the List.

2017-07-15 21:02 UTC, HHS81 commented on Nasal/rotor_wash.nas
> +# Preflight control surface check: elevator
Was my mistake

2017-07-15 21:11 UTC, HHS81 commented on Nasal/rotor_wash.nas
> +settimer (wash_loop, 0.0);
https://sourceforge.net/p/flightgear/mailman/message/35918338/

2017-07-16 16:20 UTC, SebDieBln commented on Nasal/rotor_wash.nas
> +settimer (wash_loop, 0.0);
On the list Thorsten asks:
> Do we have any option of running code (property rules,  
Nasal,...) for, say, view management, even when FG is paused by  
designating it in a special way?

And both, `settimer()` and `maketimer()`, provide that option. Therefore I propose implementing this for the EC135 and sending a patch upstream.

2018-11-25 13:30 UTC, merged